AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Set a Lambda notification configuration on an S3 bucket

Parameters:
  NotificationBucket:
    Type: String
    Description: S3 bucket that's used for the Lambda event notification
    ConstraintDescription: >-
      Must a bucket name
  LambdaFunctionArn:
    Type: String
    Description: The S3 lambda function ARN
    ConstraintDescription: >-
      Must be the lambda function ARN
      (i.e. arn:aws:lambda:us-east-1:787179373106:function:my-lambda-S3SynpaseSyncFunction)
  LambdaNotificationEvents:
    Type: CommaDelimitedList
    Description: The lambda function events for the S3 bucket notification configuration
    ConstraintDescription: >-
      Must be a list of s3 events (i.e. ["s3:ObjectCreated:*", "s3:ObjectRemoved:*"])

Resources:
  LambdaConfigurationBucketPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetBucketNotification'
              - 's3:PutBucketNotification'
            Resource: !Sub 'arn:aws:s3:::${NotificationBucket}'

  LambdaConfigurationRole:   # execute lambda function with this role
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref LambdaConfigurationBucketPolicy

  LambdaConfigurationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Role: !GetAtt LambdaConfigurationRole.Arn
      CodeUri: lambda_configuration/
      Runtime: python3.6
      Timeout: 50
      Environment:
        Variables:
          BUCKET_NAME: !Ref NotificationBucket
          LAMBDA_FUNCTION_ARN: !Ref LambdaFunctionArn
          LAMBDA_NOTIFICATION_EVENTS: !Ref LambdaNotificationEvents

Outputs:
  LambdaConfigurationFunctionArn:
    Description: "LambdaConfigurationFunction Function ARN"
    Value: !GetAtt LambdaConfigurationFunction.Arn
  LambdaConfigurationRoleArn:
    Description: "LambdaConfigurationRole function role ARN"
    Value: !GetAtt LambdaConfigurationRole.Arn
